### ISSUE TITLE
Feature Request: Unzip/unarchive (possibly conditional)

### ISSUE THREAD

**Issue by andrew-luminal** [fugue/zim#15]
### Unzip/unarchive

Unzips or unarchives the tar/zip created by `zip` or `archive`. Suggested syntax:

```
commands
  - unzip
      input:
      output:
```

Possible option to do this conditionally, which would help out a lot for the "this folder needs to exist to build" use-cases:

```
commands
  - unarchive
      condition: ! -d "node_modules"
      input: ../../artifacts/${NAME}.node_modules.tgz
      output: .
```

**Comment by curtis-fugue** [comment]
Done in https://github.com/fugue/zim/pull/20
